export enum EntityType {
  Plan = "Plan",
  Suscription = "Suscription",
  Company = "Company",
  Unit = "Unit",
  Branch = "Branch",
  Role = "Role",
  Category = "Category",
  User = "User",
  Product = "Product",
  CashRegister = "CashRegister",
  Purchase = "Purchase",
  PurchaseItem = "PurchaseItem",
  CashMovement = "CashMovement",
  Sale = "Sale",
  Inventory = "Inventory",
  InventoryMovement = "InventoryMovement",
  ProductUnit = "ProductUnit",
  SaleItem = "SaleItem",
  Log = "Log"
}